image: gcr.io/kaniko-project/executor:debug

stages:
  - tests
  - build
  - deploy

run-pytest:
  stage: tests
  image:
    name: mateusoliveira43/poetry:1.4-python3.11
  script:
    - cd backend
    - poetry install
    - poetry run pytest

build-docker-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/docker/backend.dockerfile"
      --target "prod"
      --force
      --destination "${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_SHORT_SHA}"
  retry: 2
  except:
    refs:
      - main

build-docker-prod-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/docker/backend.dockerfile"
      --target "prod"
      --force
      --destination "${CI_REGISTRY_IMAGE}/backend:latest"
  only:
    refs:
      - main
  retry: 2

deploy:
  stage: deploy
  image:
    name: curlimages/curl
  script:
    # backend setup
    - curl -X POST https://portainer.sifs0005.infs.ch/api/webhooks/518e677a-d5da-4bed-8532-9d26718e2603
    # cleanup service
    - curl -X POST https://portainer.sifs0005.infs.ch/api/webhooks/ceca8964-4ae9-4301-ae47-86d6ba0330ca
    ## backend
    - curl -X POST https://portainer.sifs0005.infs.ch/api/webhooks/e8649b61-2a94-4351-abca-18424231211c 
  only:
    refs:
      - main
  retry: 2
