image: docker:23.0.2

stages:
  - tests
  - build
  - deploy

run-pytest:
  stage: tests
  script:
    - docker compose -f docker-compose.testing.yml build --quiet
    - docker compose -f docker-compose.testing.yml up -d --quiet-pull
    - docker compose -f docker-compose.testing.yml run --rm backend poetry run pytest
    - docker compose -f docker-compose.testing.yml run --rm backend poetry run mypy .
    - docker compose -f docker-compose.testing.yml down -v --remove-orphans || true

build-docker-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/docker/backend.dockerfile"
      --target "prod"
      --force
      --destination "${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_SHORT_SHA}"
  retry: 2
  except:
    refs:
      - main

build-docker-prod-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/docker/backend.dockerfile"
      --target "prod"
      --force
      --destination "${CI_REGISTRY_IMAGE}/backend:latest"
  only:
    refs:
      - main
  retry: 2

deploy:
  stage: deploy
  image:
    name: curlimages/curl
  script:
    # backend setup
    - curl -f -X POST ${BACKEND_SETUP_TRIGGER}
    # cleanup service
    - curl -f -X POST ${CLEANUP_SERVICE_TRIGGER}
    ## backend
    - curl -f -X POST ${BACKEND_TRIGGER}
  only:
    refs:
      - main
  retry: 2
