image: gcr.io/kaniko-project/executor:debug

services:
  - docker:dind

stages:
  - build
  - deploy

build-docker-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/docker/backend.dockerfile"
      --target "deploy"
      --force
      --destination "${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_SHORT_SHA}"
  retry: 2
  except:
    refs:
      - main

build-docker-prod-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/docker/backend.dockerfile"
      --target "deploy"
      --force
      --destination "${CI_REGISTRY_IMAGE}/backend:latest"
  only:
    refs:
      - main
  retry: 2

deploy:
  stage: deploy
  image:
    name: python:3
  script:
    - python -m pip install httpie
    # backend setup
    #- http POST 
    ## backend
    #- http POST 
    ## frontend
    #- http POST 
  only:
    refs:
      - main
  retry: 2
