# Generated by Django 4.1.6 on 2023-02-14 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('usage', models.TextField(blank=True, default='')),
                (
                    'server_type',
                    models.CharField(
                        choices=[('superset', 'Superset (Hetzner)')],
                        max_length=40,
                    ),
                ),
                ('server_id', models.CharField(max_length=255)),
                ('address', models.URLField(blank=True, null=True)),
                (
                    'server_user',
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    'server_password',
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
