# Generated by Django 4.1.7 on 2023-02-15 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerVariant',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type_id',
                    models.CharField(
                        help_text='ensure text is spaces free', max_length=40
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='user facing text', max_length=250
                    ),
                ),
                ('instance_type', models.CharField(max_length=10)),
                (
                    'image_name',
                    models.CharField(
                        help_text='snapshots do not have a name, only a description. ensure the description (ie. `superset`) is unique in the corresponding project space. this image (snapshot) needs to exist on the hetzner server, else this action fails.',
                        max_length=250,
                    ),
                ),
                (
                    'location',
                    models.CharField(
                        default='nbg1',
                        help_text='the location must be the same as the location of the snapshot.',
                        max_length=20,
                    ),
                ),
                (
                    'description',
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    'setup_reference',
                    models.URLField(
                        default='https://gitlab.ost.ch/ifs/infrastructure/setup_scripts',
                        max_length=250,
                    ),
                ),
                ('user_message', models.TextField(blank=True, null=True)),
                (
                    'remove_after_minutes',
                    models.IntegerField(
                        default=240, help_text='default is 4h.'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('usage', models.TextField(blank=True, default='')),
                ('user_message', models.TextField(blank=True, null=True)),
                ('removal_at', models.DateTimeField()),
                ('server_id', models.CharField(max_length=255)),
                ('server_name', models.CharField(default='', max_length=255)),
                ('server_address', models.URLField(blank=True, null=True)),
                (
                    'server_user',
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    'server_password',
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    'server_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='server_mgr.servervariant',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
