# Generated by Django 4.1.6 on 2023-02-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='address',
            new_name='server_address',
        ),
    ]
