# Generated by Django 4.1.7 on 2023-02-15 16:44

from django.db import migrations


def create_superset_server_variant(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ServerVariant = apps.get_model('server_mgr', 'ServerVariant')
    ServerVariant(
        type_id='superset',
        name='Superset (Hetzner)',
        instance_type='cx21',
        location='nbg1',
        # this image (snaphsot) needs to exist on the
        # hetzner server, else this action fails.
        image_name='superset',
        description='Superset Instance, running on Hetzner',
        # the next setting isn't used, setup and script would need to be adapted.
        # most likely it is a better idea to use terraform or pulumi for this.
        # but like this, we at least know where to look for the setup script
        setup_reference='https://gitlab.ost.ch/ifs/infrastructure/setup_scripts/-/raw/main/superset/setup.sh',
        user_message="""Your instance should soon (usually within 3 minutes) be available at 
<a target="_blank" href="http://{{ server.server_address }}:8088">http://{{ server.server_address }}:8088</a>.
It will be active until {{ server.removal_at|date:"H:i:s (d-m-y)" }} and then destroyed (including your data!).<br />
You can login using the standard username <code>admin</code> and password <code>admin</code>.
Your Server credentials can be found under details.<br />""",
        remove_after_minutes=4 * 60,
    ).save()


def delete_superset_server_variant(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ServerVariant = apps.get_model('server_mgr', 'ServerVariant')
    ServerVariant.objects.filter(type_id='superset').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_superset_server_variant, delete_superset_server_variant
        ),
    ]
