# Generated by Django 4.1.7 on 2023-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0002_auto_20230215_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='notify_before_destroy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servervariant',
            name='notify_before_destroy',
            field=models.BooleanField(
                default=False,
                help_text='notify user before deletion of server',
            ),
        ),
    ]
