# Generated by Django 4.1.6 on 2023-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0002_rename_address_server_server_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='user_massage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
