# Generated by Django 4.1.7 on 2023-02-15 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0003_server_user_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='removal_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
