# Generated by Django 4.1.7 on 2023-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0003_server_notify_before_destroy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='info_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
