# Generated by Django 4.1.7 on 2023-02-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0004_server_info_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='extending_lifetime_secret',
            field=models.UUIDField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
    ]
