# Generated by Django 4.1.7 on 2023-02-15 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0004_server_removal_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='removal_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
