# Generated by Django 4.1.7 on 2023-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0005_alter_server_removal_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
