# Generated by Django 4.1.7 on 2023-02-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0005_server_extending_lifetime_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servervariant',
            name='notify_before_destroy',
            field=models.BooleanField(
                default=False,
                help_text='Default settings for notify user before deletion of server',
            ),
        ),
    ]
