# Generated by Django 4.1.7 on 2023-02-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('server_mgr', '0006_alter_servervariant_notify_before_destroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='servervariant',
            name='allowed_groups',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='None for allowed for everyone. Select groups to limit access to the template.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='auth.group',
            ),
        ),
    ]
