# Generated by Django 4.1.7 on 2023-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0007_rename_user_massage_server_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='removal_at',
            field=models.DateTimeField(),
        ),
    ]
