# Generated by Django 4.1.7 on 2023-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('server_mgr', '0007_servervariant_allowed_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servervariant',
            name='allowed_groups',
        ),
        migrations.AddField(
            model_name='servervariant',
            name='allowed_groups',
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text='None for allowed for everyone. Select groups to limit access to the template.',
                null=True,
                to='auth.group',
            ),
        ),
    ]
