# Generated by Django 4.1.7 on 2023-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('server_mgr', '0008_remove_servervariant_allowed_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servervariant',
            name='allowed_groups',
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text='None for allowed for everyone. Select groups to limit access to the template.',
                to='auth.group',
            ),
        ),
    ]
