# Generated by Django 4.1.7 on 2023-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0009_alter_servervariant_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='prolong_by_days',
            field=models.IntegerField(
                blank=True,
                default=None,
                editable=False,
                help_text='if set, allow prolonging by this amount of days. 365 is a year, nicola ;-).',
                null=True,
            ),
        ),
    ]
