# Generated by Django 4.1.7 on 2023-02-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mgr', '0011_remove_server_prolong_by_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servervariant',
            name='prolong_by_days',
            field=models.IntegerField(blank=True, default=None, help_text='if set, allow prolonging by this amount of days. 365 is a year, nicola ;-).', null=True),
        ),
    ]
