# Generated by Django 4.2 on 2023-04-04 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Message at creation time for the user')),
                ('max_paralell_executions', models.IntegerField(blank=True, default=0, help_text='If set, only as many jobs for one action (creation, deletionetc) are allowed. They are retried until the limit is OK again. 0 for unlimited.')),
                ('remove_after_minutes', models.IntegerField(default=240, help_text='default is 4h.')),
                ('user_message', models.TextField(blank=True, null=True)),
                ('notify_before_destroy', models.BooleanField(default=False, help_text='Default settings for notify user before deletion of server')),
                ('prolong_by_days', models.IntegerField(blank=True, default=None, help_text='if set, allow prolonging by this amount of days is allowed. 365 days is a year.', null=True)),
                ('server_type_reference', models.CharField(max_length=200, unique=True)),
                ('template_params', models.JSONField(blank=True, help_text='if allowed by the template, this will be passed along when creating the server.', null=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, default=None, help_text='None for allowed for everyone. Select groups to limit access to the template.', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionedServerInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('usage', models.TextField(blank=True, default='')),
                ('user_message', models.TextField(blank=True, null=True)),
                ('removal_at', models.DateTimeField()),
                ('server_id', models.CharField(max_length=255)),
                ('server_name', models.CharField(default='', max_length=255)),
                ('server_address', models.URLField(blank=True, null=True)),
                ('server_user', models.TextField(blank=True, null=True)),
                ('server_password', models.TextField(blank=True, null=True)),
                ('notify_before_destroy', models.BooleanField(default=False)),
                ('info_mail_sent', models.BooleanField(default=False)),
                ('extending_lifetime_secret', models.UUIDField(blank=True, default=None, editable=False, null=True)),
                ('server_state', models.IntegerField(choices=[(-1, 'ERROR'), (10, 'CREATING'), (20, 'RUNNING'), (30, 'STOPPED'), (1000, 'UNKNOWN')], default=1000)),
                ('server_bears_mark_of_deletion', models.BooleanField(default=False)),
                ('server_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.servertype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutionMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('job_id', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('user_message', models.TextField(blank=True, null=True)),
                ('user_trace', models.TextField(blank=True, null=True)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('admin_trace', models.TextField(blank=True, null=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.provisionedserverinstance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
